### ISSUE TITLE
Add Animation Buttons

### ISSUE THREAD

**Issue by Julez404** [Julez404/PixelTable#10]
# On Page "Animation" add:

- [x] __Button__: Rainbow
  * __Call function__: setAnimation.php?animation=rainbow
- [x] __Button__: theaterChase - Rainbow:
  * __Call function__: setAnimation.php?animation=theaterChaseRainbow
- [x] Running Magazine
  * __Text Field__: Message
  * __Button__: Send
    * __Call function__: runningMagazine.php?message=(The input String)

**Comment by Julez404** [comment]
function call "runningMagazine.php" is not yet implemented

**Comment by Julez404** [comment]
Animation Buttons are not on Page "Animations"

**Comment by IDookii** [comment]
setAnimation.php?animation=runningMagazine&string="string"
