### ISSUE TITLE
Static picture save

### ISSUE THREAD

**Issue by IDookii** [Julez404/PixelTable#14]
Lets discuss.
Where and how?

**Comment by Julez404** [comment]
Following functions will be implemented
- [ ] setPicture, parameter = picture
- [ ] delPicture, parameter = picture
- [ ] savePicture, parameter = name of new picture
- [ ] getAllPicture, returns string of all saved Pictures, _seperatet

**Comment by IDookii** [comment]
These characters include digits (0-9), letters(A-Z, a-z), and a few special characters ("-", "_").
