### ISSUE TITLE
eye dropper, what functions need to be implemented?

### ISSUE THREAD

**Issue by Julez404** [Julez404/PixelTable#30]
@IDookii Info pls

**Comment by IDookii** [comment]
Ill give you:
   getPixel.php?row=" + _row + "&column=" + _column,
You return:
color=_color

**Comment by Julez404** [comment]
getPixel.php?...   Now returns -010F1D-    (Example Value)
I added "-" as seperator before and after the color for easier extraction

**Comment by Julez404** [comment]
Changed behavior to "x_y_color" as in html file.
Functions works as intendet -- closed
