### ISSUE TITLE
Better addressing of individual LED

### ISSUE THREAD

**Issue by Julez404** [Julez404/PixelTable#5]
Create grid for better ux on website

Is a readback function needed? 
Table -> Website?

**Comment by IDookii** [comment]
Szenario
Tisch aht standbild, eingestellt per Hand
Du gehst auf website
Dann ist da aber die Website blank
Hätte diese funktion nur für standbilder imple

**Comment by Julez404** [comment]
Die Standardfarbe ist Weiß, sollte man eine LED ausschalten wollen, färbt diese sich schwarz. Inkonsistentes Verhalten.
